name: build

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker build -t quay.io/yuvipanda/nbss:main .
          docker push quay.io/yuvipanda/nbss:main
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}